apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: base-vm 
  name: base-vm
  namespace: gitops-ocp-virt-demo
spec:    
    running: false
    template:
      metadata:
        labels:
          kubevirt.io/domain: base-vm
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 1
            threads: 1
          memory:
            guest: 2048M
          devices:
            disks:
            - disk:
                bus: virtio
              name: vm-rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - masquerade: {}
              name: default
            rng: {}
          features:
            smm:
              enabled: true
          firmware:
            bootloader:
              efi: {}
          resources:
            requests:
              memory: 2Gi
        evictionStrategy: LiveMigrate
        networks:
        - name: default
          pod: {}
        volumes:
        - persistentVolumeClaim:
              claimName: base-vm-disk
          name: vm-rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: piros
              password: 'password' 
              chpasswd: { expire: False }
          name: cloudinitdisk
